### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by drk77** [Telariust/pollard-kangaroo-c99#1]
gcc -O2 -I secp256k1/src/ -I secp256k1/ pollard-kangaroo.c -lgmp
pollard-kangaroo.c:230:53: warning: ‘struct tm’ declared inside parameter list will not be visible outside of this definition or declaration
 void passtime_old(char *s, size_t max, const struct tm *tm){
                                                     ^~
pollard-kangaroo.c: In function ‘passtime_old’:
pollard-kangaroo.c:231:58: error: dereferencing pointer to incomplete type ‘const struct tm’
  snprintf(s, max, "%01iy %01im %01id %02i:%02i:%02is", tm->tm_year-70, tm->tm_mon, tm->tm_mday-1, tm->tm_hour, tm->tm_min, tm->tm_sec);
                                                          ^~
pollard-kangaroo.c: At top level:
pollard-kangaroo.c:234:49: warning: ‘struct tm’ declared inside parameter list will not be visible outside of this definition or declaration
 void passtime(char *s, size_t max, const struct tm *tm){
                                                 ^~
pollard-kangaroo.c: In function ‘passtime’:
pollard-kangaroo.c:236:8: error: dereferencing pointer to incomplete type ‘const struct tm’
  if( tm->tm_year-70 > 0 ){
        ^~
pollard-kangaroo.c: In function ‘main’:
pollard-kangaroo.c:353:35: warning: implicit declaration of function ‘time’; did you mean ‘utimes’? [-Wimplicit-function-declaration]
  timetotal = timelast = timenow = time(NULL);
                                   ^~~~
                                   utimes
pollard-kangaroo.c:375:2: warning: implicit declaration of function ‘strftime’ [-Wimplicit-function-declaration]
  strftime(timebuff, sizeof(timebuff), "%d %b %Y %H:%M:%S", gmtime(&timenow));
  ^~~~~~~~
pollard-kangaroo.c:375:2: warning: incompatible implicit declaration of built-in function ‘strftime’
pollard-kangaroo.c:375:2: note: include ‘<time.h>’ or provide a declaration of ‘strftime’
pollard-kangaroo.c:17:1:
+#include <time.h>
 
pollard-kangaroo.c:375:2:
  strftime(timebuff, sizeof(timebuff), "%d %b %Y %H:%M:%S", gmtime(&timenow));
  ^~~~~~~~
pollard-kangaroo.c:375:60: warning: implicit declaration of function ‘gmtime’; did you mean ‘futimes’? [-Wimplicit-function-declaration]
  strftime(timebuff, sizeof(timebuff), "%d %b %Y %H:%M:%S", gmtime(&timenow));
                                                            ^~~~~~
                                                            futimes
pollard-kangaroo.c:375:60: warning: passing argument 4 of ‘strftime’ makes pointer from integer without a cast [-Wint-conversion]
  strftime(timebuff, sizeof(timebuff), "%d %b %Y %H:%M:%S", gmtime(&timenow));
                                                            ^~~~~~~~~~~~~~~~
pollard-kangaroo.c:375:60: note: expected ‘const void *’ but argument is of type ‘int’
pollard-kangaroo.c:399:54: warning: format ‘%X’ expects argument of type ‘unsigned int *’, but argument 3 has type ‘unsigned char *’ [-Wformat=]
     for(int i=0; i<32 ; ++i){sscanf(&buff_L[2*i],"%02X",&buff_b32[i+((64-strlen(buff_L))/2)]);}
                                                   ~~~^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   %02hhX
pollard-kangaroo.c:404:56: warning: format ‘%X’ expects argument of type ‘unsigned int *’, but argument 3 has type ‘unsigned char *’ [-Wformat=]
     for(int i=0; i<32 ; ++i){sscanf(&buff_02X[2*i],"%02X",&buff_b32[i+((64-strlen(buff_02X))/2)]);}
                                                     ~~~^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                     %02hhX
pollard-kangaroo.c:422:54: warning: format ‘%X’ expects argument of type ‘unsigned int *’, but argument 3 has type ‘unsigned char *’ [-Wformat=]
     for(int i=0; i<32 ; ++i){sscanf(&buff_U[2*i],"%02X",&buff_b32[i+((64-strlen(buff_U))/2)]);}
                                                   ~~~^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                   %02hhX
pollard-kangaroo.c:427:56: warning: format ‘%X’ expects argument of type ‘unsigned int *’, but argument 3 has type ‘unsigned char *’ [-Wformat=]
     for(int i=0; i<32 ; ++i){sscanf(&buff_02X[2*i],"%02X",&buff_b32[i+((64-strlen(buff_02X))/2)]);}
                                                     ~~~^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                     %02hhX
pollard-kangaroo.c:571:22: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  printf("\n[DPsize] %u (hashtable size)", maxDP);
                     ~^                    ~~~~~
                     %lu
pollard-kangaroo.c:598:59: warning: format ‘%X’ expects argument of type ‘unsigned int *’, but argument 3 has type ‘unsigned char *’ [-Wformat=]
   for(int i=0; i<LEN_PUBK ; ++i){sscanf(&argv[2][2*i],"%02X",&new_pubkey[i]);}
                                                        ~~~^  ~~~~~~~~~~~~~~
                                                        %02hhX
pollard-kangaroo.c:994:60: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
        printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
                                                           ~^                    ~~~~
                                                           %lu
pollard-kangaroo.c:994:63: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
        printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
                                                              ~^                       ~~~~
                                                              %lu
pollard-kangaroo.c:994:66: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
        printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
                                                                 ~^                          ~~~~~~~~~
                                                                 %lu
pollard-kangaroo.c:994:74: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 5 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
   printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
                                                                    ~^                             ~~~~~
                                                                    %lu
pollard-kangaroo.c:1112:60: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
        printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
                                                           ~^                    ~~~~
                                                           %lu
pollard-kangaroo.c:1112:63: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
        printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
                                                              ~^                       ~~~~
                                                              %lu
pollard-kangaroo.c:1112:66: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
        printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
                                                                 ~^                          ~~~~~~~~~
                                                                 %lu
pollard-kangaroo.c:1112:74: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 5 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
   printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
                                                                    ~^                             ~~~~~
                                                                    %lu
pollard-kangaroo.c:1199:15: warning: implicit declaration of function ‘difftime’; did you mean ‘passtime’? [-Wimplicit-function-declaration]
    timepass = difftime(timenow,timelast);
               ^~~~~~~~
               passtime
pollard-kangaroo.c:1204:92: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 6 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
 rintf("\r[i] DP T+W=%lu+%lu=%lu; dp/kgr=%.1lf; HashTableCollisions=%u                  \n"
                                                                    ~^
                                                                    %lu
 n_DW, (float)(n_DT+n_DW)/2, n_coll);
                             ~~~~~~                                   

pollard-kangaroo.c:1209:42: warning: passing argument 3 of ‘passtime’ makes pointer from integer without a cast [-Wint-conversion]
     passtime(timebuff, sizeof(timebuff), gmtime(&timepass));
                                          ^~~~~~~~~~~~~~~~~
pollard-kangaroo.c:234:53: note: expected ‘const struct tm *’ but argument is of type ‘int’
 void passtime(char *s, size_t max, const struct tm *tm){
                                    ~~~~~~~~~~~~~~~~~^~
pollard-kangaroo.c:1234:44: warning: passing argument 3 of ‘passtime’ makes pointer from integer without a cast [-Wint-conversion]
       passtime(timebuff, sizeof(timebuff), gmtime(&timepass));
                                            ^~~~~~~~~~~~~~~~~
pollard-kangaroo.c:234:53: note: expected ‘const struct tm *’ but argument is of type ‘int’
 void passtime(char *s, size_t max, const struct tm *tm){
                                    ~~~~~~~~~~~~~~~~~^~
pollard-kangaroo.c:1238:44: warning: passing argument 3 of ‘passtime’ makes pointer from integer without a cast [-Wint-conversion]
       passtime(timebuff, sizeof(timebuff), gmtime(&timepass));
                                            ^~~~~~~~~~~~~~~~~
pollard-kangaroo.c:234:53: note: expected ‘const struct tm *’ but argument is of type ‘int’
 void passtime(char *s, size_t max, const struct tm *tm){
                                    ~~~~~~~~~~~~~~~~~^~
pollard-kangaroo.c:1368:39: warning: passing argument 3 of ‘passtime’ makes pointer from integer without a cast [-Wint-conversion]
  passtime(timebuff, sizeof(timebuff), gmtime(&timepass));
                                       ^~~~~~~~~~~~~~~~~
pollard-kangaroo.c:234:53: note: expected ‘const struct tm *’ but argument is of type ‘int’
 void passtime(char *s, size_t max, const struct tm *tm){
                                    ~~~~~~~~~~~~~~~~~^~
pollard-kangaroo.c:1390:60: warning: passing argument 4 of ‘strftime’ makes pointer from integer without a cast [-Wint-conversion]
  strftime(timebuff, sizeof(timebuff), "%d %b %Y %H:%M:%S", gmtime(&timenow));
                                                            ^~~~~~~~~~~~~~~~
pollard-kangaroo.c:1390:60: note: expected ‘const void *’ but argument is of type ‘int’

**Comment by saama143** [comment]
> gcc -O2 -I secp256k1/src/ -I secp256k1/ pollard-kangaroo.c -lgmp
> pollard-kangaroo.c:230:53: warning: ‘struct tm’ declared inside parameter list will not be visible outside of this definition or declaration
> void passtime_old(char *s, size_t max, const struct tm *tm){
> ^~
> pollard-kangaroo.c: In function ‘passtime_old’:
> pollard-kangaroo.c:231:58: error: dereferencing pointer to incomplete type ‘const struct tm’
> snprintf(s, max, "%01iy %01im %01id %02i:%02i:%02is", tm->tm_year-70, tm->tm_mon, tm->tm_mday-1, tm->tm_hour, tm->tm_min, tm->tm_sec);
> ^~
> pollard-kangaroo.c: At top level:
> pollard-kangaroo.c:234:49: warning: ‘struct tm’ declared inside parameter list will not be visible outside of this definition or declaration
> void passtime(char *s, size_t max, const struct tm *tm){
> ^~
> pollard-kangaroo.c: In function ‘passtime’:
> pollard-kangaroo.c:236:8: error: dereferencing pointer to incomplete type ‘const struct tm’
> if( tm->tm_year-70 > 0 ){
> ^~
> pollard-kangaroo.c: In function ‘main’:
> pollard-kangaroo.c:353:35: warning: implicit declaration of function ‘time’; did you mean ‘utimes’? [-Wimplicit-function-declaration]
> timetotal = timelast = timenow = time(NULL);
> ^~~~
> utimes
> pollard-kangaroo.c:375:2: warning: implicit declaration of function ‘strftime’ [-Wimplicit-function-declaration]
> strftime(timebuff, sizeof(timebuff), "%d %b %Y %H:%M:%S", gmtime(&timenow));
> ^~~~~~~~
> pollard-kangaroo.c:375:2: warning: incompatible implicit declaration of built-in function ‘strftime’
> pollard-kangaroo.c:375:2: note: include ‘<time.h>’ or provide a declaration of ‘strftime’
> pollard-kangaroo.c:17:1:
> +#include <time.h>
> 
> pollard-kangaroo.c:375:2:
> strftime(timebuff, sizeof(timebuff), "%d %b %Y %H:%M:%S", gmtime(&timenow));
> ^~~~~~~~
> pollard-kangaroo.c:375:60: warning: implicit declaration of function ‘gmtime’; did you mean ‘futimes’? [-Wimplicit-function-declaration]
> strftime(timebuff, sizeof(timebuff), "%d %b %Y %H:%M:%S", gmtime(&timenow));
> ^~~~~~
> futimes
> pollard-kangaroo.c:375:60: warning: passing argument 4 of ‘strftime’ makes pointer from integer without a cast [-Wint-conversion]
> strftime(timebuff, sizeof(timebuff), "%d %b %Y %H:%M:%S", gmtime(&timenow));
> ^~~~~~~~~~~~~~~~
> pollard-kangaroo.c:375:60: note: expected ‘const void *’ but argument is of type ‘int’
> pollard-kangaroo.c:399:54: warning: format ‘%X’ expects argument of type ‘unsigned int *’, but argument 3 has type ‘unsigned char _’ [-Wformat=] for(int i=0; i<32 ; ++i){sscanf(&buff_L[2_i],"%02X",&buff_b32[i+((64-strlen(buff_L))/2)]);}
> ~~~^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> %02hhX
> pollard-kangaroo.c:404:56: warning: format ‘%X’ expects argument of type ‘unsigned int *’, but argument 3 has type ‘unsigned char _’ [-Wformat=] for(int i=0; i<32 ; ++i){sscanf(&buff_02X[2_i],"%02X",&buff_b32[i+((64-strlen(buff_02X))/2)]);}
> ~~~^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> %02hhX
> pollard-kangaroo.c:422:54: warning: format ‘%X’ expects argument of type ‘unsigned int *’, but argument 3 has type ‘unsigned char _’ [-Wformat=] for(int i=0; i<32 ; ++i){sscanf(&buff_U[2_i],"%02X",&buff_b32[i+((64-strlen(buff_U))/2)]);}
> ~~~^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> %02hhX
> pollard-kangaroo.c:427:56: warning: format ‘%X’ expects argument of type ‘unsigned int *’, but argument 3 has type ‘unsigned char _’ [-Wformat=] for(int i=0; i<32 ; ++i){sscanf(&buff_02X[2_i],"%02X",&buff_b32[i+((64-strlen(buff_02X))/2)]);}
> ~~~^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> %02hhX
> pollard-kangaroo.c:571:22: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
> printf("\n[DPsize] %u (hashtable size)", maxDP);
> ~^ ~~~~~
> %lu
> pollard-kangaroo.c:598:59: warning: format ‘%X’ expects argument of type ‘unsigned int *’, but argument 3 has type ‘unsigned char _’ [-Wformat=] for(int i=0; i<LEN_PUBK ; ++i){sscanf(&argv[2][2_i],"%02X",&new_pubkey[i]);}
> ~~~^ ~~~~~~~~~~~~~~
> %02hhX
> pollard-kangaroo.c:994:60: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
> printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
> ~^ ~~~~
> %lu
> pollard-kangaroo.c:994:63: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
> printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
> ~^ ~~~~
> %lu
> pollard-kangaroo.c:994:66: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
> printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
> ~^ ~~~~~~~~~
> %lu
> pollard-kangaroo.c:994:74: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 5 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
> printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
> ~^ ~~~~~
> %lu
> pollard-kangaroo.c:1112:60: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
> printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
> ~^ ~~~~
> %lu
> pollard-kangaroo.c:1112:63: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
> printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
> ~^ ~~~~
> %lu
> pollard-kangaroo.c:1112:66: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
> printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
> ~^ ~~~~~~~~~
> %lu
> pollard-kangaroo.c:1112:74: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 5 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
> printf("\n[FATAL_ERROR] DP hashtable overflow! T+W=%u+%u=%u (max:%u)\n", n_DT, n_DW, n_DT+n_DW, maxDP);
> ~^ ~~~~~
> %lu
> pollard-kangaroo.c:1199:15: warning: implicit declaration of function ‘difftime’; did you mean ‘passtime’? [-Wimplicit-function-declaration]
> timepass = difftime(timenow,timelast);
> ^~~~~~~~
> passtime
> pollard-kangaroo.c:1204:92: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 6 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
> rintf("\r[i] DP T+W=%lu+%lu=%lu; dp/kgr=%.1lf; HashTableCollisions=%u \n"
> ~^
> %lu
> n_DW, (float)(n_DT+n_DW)/2, n_coll);
> ~~~~~~
> 
> pollard-kangaroo.c:1209:42: warning: passing argument 3 of ‘passtime’ makes pointer from integer without a cast [-Wint-conversion]
> passtime(timebuff, sizeof(timebuff), gmtime(&timepass));
> ^~~~~~~~~~~~~~~~~
> pollard-kangaroo.c:234:53: note: expected ‘const struct tm *’ but argument is of type ‘int’
> void passtime(char *s, size_t max, const struct tm *tm){
> ~~~~~~~~~~~~~~~~~^~
> pollard-kangaroo.c44: warning: passing argument 3 of ‘passtime’ makes pointer from integer without a cast [-Wint-conversion]
> passtime(timebuff, sizeof(timebuff), gmtime(&timepass));
> ^~~~~~~~~~~~~~~~~
> pollard-kangaroo.c:234:53: note: expected ‘const struct tm *’ but argument is of type ‘int’
> void passtime(char *s, size_t max, const struct tm *tm){
> ~~~~~~~~~~~~~~~~~^~
> pollard-kangaroo.c:1238:44: warning: passing argument 3 of ‘passtime’ makes pointer from integer without a cast [-Wint-conversion]
> passtime(timebuff, sizeof(timebuff), gmtime(&timepass));
> ^~~~~~~~~~~~~~~~~
> pollard-kangaroo.c:234:53: note: expected ‘const struct tm *’ but argument is of type ‘int’
> void passtime(char *s, size_t max, const struct tm *tm){
> ~~~~~~~~~~~~~~~~~^~
> pollard-kangaroo.c:1368:39: warning: passing argument 3 of ‘passtime’ makes pointer from integer without a cast [-Wint-conversion]
> passtime(timebuff, sizeof(timebuff), gmtime(&timepass));
> ^~~~~~~~~~~~~~~~~
> pollard-kangaroo.c:234:53: note: expected ‘const struct tm *’ but argument is of type ‘int’
> void passtime(char *s, size_t max, const struct tm *tm){
> ~~~~~~~~~~~~~~~~~^~
> pollard-kangaroo.c:1390:60: warning: passing argument 4 of ‘strftime’ makes pointer from integer without a cast [-Wint-conversion]
> strftime(timebuff, sizeof(timebuff), "%d %b %Y %H:%M:%S", gmtime(&timenow));
> ^~~~~~~~~~~~~~~~
> pollard-kangaroo.c:1390:60: note: expected ‘const void *’ but argument is of type ‘int’

Did you find the soltion for that? I am also getting same error.

**Comment by kenni4** [comment]
You have to add in header
#include <time.h>

and compile with
gcc -O3 -I secp256k1/src/ -I secp256k1/ pollard-kangaroo.c -lgmp -lm -o kangaroo

**Comment by Telariust** [comment]
update 0.21
 - fixed not exist time.h
 - fixed  -Wformat=1 minor warnings

in u system need flag "-lm" for success "#include <math.h>" ? ok, maybe..
