### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by su314ka** [Telariust/pollard-kangaroo-c99#2]
Hi,

Let say that I want to use the tool for an address like 12ib7dApVFvg82TXKycWBNpN8kFyiAN1dr
with the public key 04d6597d465408e6e11264c116dd98b539740e802dc756d7eb88741696e20dfe7d3588695d2e7ad23cbf0aa056d42afada63036d66a1d9b97070dd6bc0c87ceb0d

or for the 1A7kH6BLaYLPNKtgrPGuBSbhHM6HoGdpu3 with 03d6597d465408e6e11264c116dd98b539740e802dc756d7eb88741696e20dfe7d

What should be the syntax? How can I run it? Thanks!

**Comment by Telariust** [comment]
its pollard-kangaroo, i.e. you must know in advance the area where approximately private key is located;
specify bits or range with first argument (in hex);

address base58 (same ripemd160hash) useless, but pubkey is required.
specify pubkey with second argument (in hex);

example run:
`>pollard-kangaroo 50 04d6597d465408e6e11264c116dd98b539740e802dc756d7eb88741696e20dfe7d3588695d2e7ad23cbf0aa056d42afada63036d66a1d9b97070dd6bc0c87ceb0d`
`>pollard-kangaroo 9ABCDEF123:F34567890A 03d6597d465408e6e11264c116dd98b539740e802dc756d7eb88741696e20dfe7d`

if pair pubkey+prvkey does not actually lie inside the range, then expected runtime will be many times exceeded and in the final the storage of distinguished points will exceed the limit.
(when the percentage of completion exceeds 300% it already speaks of an invalid range)
