### ISSUE TITLE
custom range problem 

### ISSUE THREAD

**Issue by solwhitey** [Telariust/pollard-kangaroo-c99#6]
Hi, first, thanks for your code ! Really useful !
I have a problem, for example, when I chose a custom range for #65, the program put number before my real range which give this : 

> root@vultr:~# ./kang 116345785D8A00000:22C68AF0BB1400000  0230210c23b1a047bc9bdbb13448e67deddc108946de6de639bcc75d47c0216b1b

> [###########################################################]
> [#          Pollard-kangaroo PrivKey Recovery Tool         #]
> [#            C99, bitcoin-core/secp256k1 library          #]
> [#                        singlecore                       #]
> [#                          ver0.23                        #]
> [###########################################################]
> [DATE(utc)] 02 Oct 2019 22:54:49
> [~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
> [i] custom range loaded from argv1
> [L] (~2^64) 0x00000000000000000000000000000000000000000000000116345785D8A00000
> [U] (~2^137) 0x00000000000000000000000000000116345785D8A0000022C68AF0BB14000000
> [W] (~2^137) 0x00000000000000000000000000000116345785D8A0000021B05699353B600000
> 
> [FATAL_ERROR] bits must be 2^8..2^130!
> 
> 
> [usage] ./kang [bits] [pubkey]
>         ./kang 40
>         ./kang 40 03A2EFA402FD5268400C77C20E574BA86409EDEDEE7C4020E4B9F0EDBEE53DE0D4
> 
> [usage] ./kang [start:end] [pubkey]
>         ./kang 9ABCDEF123:F34567890A 03A2EFA402FD5268400C77C20E574BA86409EDEDEE7C4020E4B9F0EDBEE53DE0D4**
> 

The U and W are as big as #137, why ?

Also, do you have an ETA approximately for the GPU or Multi Threaded code on C99 ?
Thanks for your help !

**Comment by hamnaz** [comment]
116345785D8A00000:22C68AF0BB1400000 
116345785D8A00000   65
22C68AF0BB1400000   66

your 2nd rang is 66
65 rang end at
1ffffffffffffffffffffffffffff

**Comment by solwhitey** [comment]
Yes I know but for #47 i can use custom range with my first range in 47 and second in 48 and it work.

> root@vultr:~# ./kang 500000000000:900000000000 023a12bd3caf0b0f77bf4eea8e7a40dbe27932bf80b19ac72f5f5a64925a594196
> 
> [###########################################################]
> [#          Pollard-kangaroo PrivKey Recovery Tool         #]
> [#            C99, bitcoin-core/secp256k1 library          #]
> [#                        singlecore                       #]
> [#                          ver0.23                        #]
> [###########################################################]
> [DATE(utc)] 03 Oct 2019 14:42:59
> [~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
> [i] custom range loaded from argv1
> [L] (~2^46) 0x0000000000000000000000000000000000000000000000000000500000000000
> [U] (~2^48) 0x0000000000000000000000000000000000000000000000000000900000000000
> [W] (~2^46) 0x0000000000000000000000000000000000000000000000000000400000000000
> [rangeW]	2^46..2^48 ; W = U - L = 2^46
> [jumpsize]	2^27 max
> [DPsize]	1024 (hashtable size)
> [algo#0]	A + A -> A,  xA ready ; the fastest
> [~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
>  --> CUSTOM MODE
> [i] custom pubkey#48 loaded from argv2 
> [pubkey#48] 023A12BD3CAF0B0F77BF4EEA8E7A40DBE27932BF80B19AC72F5F5A64925A594196
> [i] compressed
>  --> pubkey valid!
> [~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
> [+] Sp-table of pow2 points - ready
> [~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
> [+] T+W kangaroos - ready
>  [ 00:00:06s ; 403.5K j/s;   2.1Mj 12.5%; dp/kgr=0.5; 00:00:36s ]   
> [~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
> [prvkey#48] 0x00000000000000000000000000000000000000000000000000006CD610B53CBA
> [i] success saved pair prvkey:pubkey to file '_found_prvkey.txt'
> [i] 403.8K j/s;   2.1Mj of  16.8Mj 12.7%; DP T+W=1+1=2; dp/kgr=1.0;
> [#############################; passtime:          00:00:06s]
> [####################################; precision:   5s 262ms]
> [~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
> [DATE(utc)] 03 Oct 2019 14:43:05
> [~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]
> [x] EXIT

**Comment by RB61** [comment]
> 116345785D8A00000:22C68AF0BB1400000

try this
0116345785D8A00000:022C68AF0BB1400000
it should work
I think there is a bug for odd hex digit number
