### ISSUE TITLE
may be safer to uncomment line 411 and 432

### ISSUE THREAD

**Issue by RB61** [Telariust/pollard-kangaroo-c99#7]
https://github.com/Telariust/pollard-kangaroo-c99/blob/e444a6225a2d814882933b96d34cf15dc937d91f/pollard-kangaroo.c#L411

https://github.com/Telariust/pollard-kangaroo-c99/blob/e444a6225a2d814882933b96d34cf15dc937d91f/pollard-kangaroo.c#L432

and change 
memset(buff_02X, 0, sizeof(buff_02X) );
for
memset(buff_02X, 0, 65 )
otherwise you get strange ranges for odd string lengths.

**Comment by Telariust** [comment]
yes, need uncomment, thx for help!
